First set of updates to make HARK both Py2 and Py3 compatible. The application:  SolvingMicroDSOPs/StructEstimation.py  under this commit now runs under both Python 2.7 and 2.6 (specifically, it has been tested under 2.7.15 and 3.6.5).
Here are the files changed to make this possible, with detailed notes following:

- modified:   ConsumptionSaving/ConsIndShockModel.py
- modified:   HARKinterpolation.py
- modified:   HARKparallel.py
- modified:   SolvingMicroDSOPs/EstimationParameters.py
- modified:   SolvingMicroDSOPs/SetupSCFdata.py

Details:

modified:   ConsumptionSaving/ConsIndShockModel.py
----------------------

- changed the "print" and "raise Exception" statements to use print('...' + str(...)) format, which is Py2 & Py3 compatible
- changed the "open(...)" mode from 'wb' to 'w'

modified:   HARKinterpolation.py
----------------------

- changed "xrange" to "range" -- NOTE that this will likely have slowing effects, regardless!

modified:   HARKparallel.py
----------------------

- changed the "raise Exception" statement to use Exception('...' + str(...)) format, which is Py2 & Py3 compatible
- changed the "open(...)" mode from 'wb' to 'w'

modified:   SolvingMicroDSOPs/EstimationParameters.py
----------------------

- Added some code to "quick fix" an error introduced in the code: "ConsumptionSaving/ConsIndShockModel.py in initializeSim(self)" -- specifically line 1523, "self.PermShkAggNow = self.PermGroFacAgg"
    - The error is "AttributeError: 'TempConsumerType' object has no attribute 'PermGroFacAgg'"
- Adding the code "init_consumer_objects['PermGroFacAgg'] = 1.0" and additional code that activates the quick fix.
- Short term: add the "quick fix" and create an "issue"
- Medium term: actually fix the issue (or decide that this fixes it).
- Long term: add unit tests to ID this in the future.

modified:   SolvingMicroDSOPs/SetupSCFdata.py
----------------------

- changed the "open(...)" mode from 'rb' to 'r'
- added a "try/except" structure to handle the different ways that csv.reader.next() executes in Py2 vs Py3