A number of changes that make the main body of HARK compatible with both Py2 and Py3.
The process was was follows:

1. Run all executable .py files under both Py2 and Py3, and "spot fix" all errors that appear during this process. There were three types of errors that appeared:
    a. "compatibility" errors between py2 and py3 that were easy to fix -- approximately 90% of the issues
    b. "compatibility" errors due to deeper differences between py2 and py3, including errors for which solutions have not yet been found.
        - specifically, the only error that has not yet been fixed is an error arising in how joblib pickles differently between py2 and py3, which I have not yet resolved. Because HARKcore.Market.solveAgents() *only* had a parallel method, the solution was to add a serial method to HARKcore.Market.solveAgents() which executes if joblib is not available.
2. Then more carefully run futurize on many (not all) executable files, and manually review each of the suggested additions, and add the additions that seemed best.
    a. on a number of occasions futurize attempted to make the Py3 code compatible with Py2 by enforcing Py2's "old_div" division command -- the notorious "integer division" -- as the way all division was done. This was a BAD IDEA and I explicitly removed all instances of that.
3. Finally, re-run all of the following files listed in the "cleared list" below manually, and visually compare all results that popped up, to ensure that py2 and py3 files were actually running. This process revealed a number of misc small errors that needed to be fixed; when that happened and a "core" HARK module was changed, I re-ran all previously run files to ensure that the new fix did not break the old fix.
    a. each "run" for a file was conducted under a "fresh" instance of Python, so as not to accidentally contaminate the namespace with previous runs. (Very time-consuming but important.)

One thing that revealed itself: often the Py3 execution times appeared ever so slightly slightly faster than the Py2 execution times, **except** for a few key examples. In particular, the ConsAggShockModel *reported* running much slower under Py3 than under Py2. However in *watching* the models execute, it was at times unclear that this was actually true -- sometimes the "time to run" reported under Py3 appeared longer than the "wall clock" time I observed. Because runtime was **not** my primary concern today (instead my primary purpose was to confirm Py2 & Py3 compatibility), I did not delve much deeper into this. We should examine it for the future, however. See the extensive "detailed notes" further below.

In general, see also the "HARK-1.wiki" github wiki pages for notes taken during this time. These are in a more "raw" form than here but catalog my effort directly.

Finally, this process illustrates the need (again) for having a set of unit tests that can be systematically run for the core files when a change is made to the code somewhere -- essentially I manually and visually did "unit test" runs when a significant change was made by futurization, but this can / should be automated.

Appendix A: Python Files That Run Under Both Py2 & Py3
======================================================

This is a short list of the files that are functional under both Python 2 and Python 3.

The *next* section outlines all files that I ran, with detailed notes about errors and times.

- [x] HARKcore.py
- [x] HARKestimation.py
- [x] HARKinterpolation.py
- [x] HARKsimulation.py
- [x] HARKutilities.py
- [x] HARKparallel.py
- ./ConsumptionSaving/
    - [x] ConsIndShockModel.py
    - [x] ConsumerParameters.py
    - [x] ConsAggShockModel.py
    - [x] TractableBufferStockModel.py
    - [x] ConsRepAgentModel.py
    - [x] ConsGenIncProcessModel.py
    - [x] ConsMedModel.py
    - [x] RepAgentModel.py
    - [x] ConsPrefShockModel.py
- ./ConsumptionSaving/
    - [x] ./ConsIndShockModel-Demos/Try-Alternative-Parameter-Values.py
    - [x] ./Demos/Fagereng_demo.py
    - [x] ./Demos/Chinese_Growth.py
    - [x] ./Demos/MPC_credit_vs_MPC_income.py
    - [x] ./Demos/NonDurables_During_Great_Recession.py
- ./FashionVictim/
    - [x] FashionVictimParams.py
    - [x] FashionVictimModel.py
- ./SolvingMicroDSOPs/
    - [x] SetupSCFdata.py
    - [x] EstimationParameters.py
    - [x] StructEstimation.py
- ./Testing/
    - [x] TractableBufferStockModel_UnitTests.py
    - [x] MultithreadDemo.py
    - [x] HARKutilities_UnitTests.py

Appendix B: Detailed Notes on All Files Run
===========================================

- [x] ./ConsumptionSaving/
    - [x] ConsIndShockModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 appears to be slightly faster:
        - Py3:
            - Solving a perfect foresight consumer took 0.1069 seconds.
            - Solving a consumer with idiosyncratic shocks took 0.3321 seconds.
            - Solving a lifecycle consumer took 0.0101 seconds.
            - Solving a cyclical consumer took 0.2033 seconds.
            - Solving a kinky consumer took 0.1273 seconds.
        - Py2:
            - Solving a perfect foresight consumer took 0.1393 seconds.
            - Solving a consumer with idiosyncratic shocks took 0.1428 seconds.
            - Solving a lifecycle consumer took 0.0091 seconds.
            - Solving a cyclical consumer took 0.2111 seconds.
            - Solving a kinky consumer took 0.1331 seconds.
    - [x] ConsumerParameters.py
        - [x] py3
        - [x] py2

- [ ] ./ConsumptionSaving/
    - [ ] ConsMarkovModel.py
        - [ ] py3: AttributeError: 'MarkovSmallOpenEconomy' object has no attribute 'PermShkAggDstn'
        - [ ] py2: AttributeError: 'MarkovSmallOpenEconomy' object has no attribute 'PermShkAggDstn'
    - [x] TractableBufferStockModel.py
        - [x] py3
        - [x] py2
    - [x] ConsRepAgentModel.py
        - [x] py3
        - [x] py2
    - [x] ConsGenIncProcessModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py2 appears to be faster:
        - Py3:
            - Solving an explicit permanent income consumer took 43.9469 seconds.
            - Solving a persistent income shocks consumer took 47.8044 seconds.
        - Py2:
            - Solving an explicit permanent income consumer took 8.3109 seconds.
            - Solving a persistent income shocks consumer took 9.7948 seconds.
    - [x] ConsMedModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 appears to be slower:
        - Py3:
            - Solving a medical shocks consumer took 140.1519 seconds.
            - Simulating 10000 agents for 100 periods took 19.5659 seconds.
        - Py2:
            - Solving a medical shocks consumer took 27.7461 seconds.
            - Simulating 10000 agents for 100 periods took 17.8634 seconds.
    - [x] RepAgentModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 appears to be mildly faster:
        - Py3:
            - Solving a representative agent problem took 0.14075600000000055 seconds.
            - Simulating a representative agent for 2000 periods took 0.48373299999999997 seconds.
            - Solving a two state representative agent problem took 0.37450399999999995 seconds.
            - Simulating a two state representative agent for 2000 periods took 0.4633750000000001 seconds.
        - Py2:
            - Solving a representative agent problem took 0.143237 seconds.
            - Simulating a representative agent for 2000 periods took 0.568245 seconds.
            - Solving a two state representative agent problem took 0.38869 seconds.
            - Simulating a two state representative agent for 2000 periods took 0.50153 seconds.
    - [x] ConsPrefShockModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 appears to be mildly faster:
        - Py3:
            - Solving a preference shock consumer took 0.33151200000000014 seconds.
            - Solving a kinky preference consumer took 0.2705059999999997 seconds.
        - Py2:
            - Solving a preference shock consumer took 0.363709 seconds.
            - Solving a kinky preference consumer took 0.29933 seconds.

- [x] ./ConsumptionSaving/
    - [x] ConsAggShockModel.py
        - [x] py3
        - [x] py2
        - Note: the Py3 version *claims* to be much slower, however the time indicated appears to be longer than the "wall clock" time for which I ran it -- I am unclear about why this is. We need to externally confirm that this code takes much longer under one vs the other. (One remote but non-trivial possibility: Py3 may have changed how the timing functions work; we need to confirm that we are recording the times that we intend to be recording when we run these).
        - Py3:
            - Now solving for the equilibrium of a Cobb-Douglas economy.  This might take a few minutes...
                - Solving the "macroeconomic" aggregate shocks model took 445.02524 seconds.
            - Now solving a two-state Markov economy.  This should take a few minutes...
                - Solving the "macroeconomic" aggregate shocks model took 744.1959099999999 seconds.
            - Now solving a Krusell-Smith-style economy.  This should take about a minute...
                - Solving the Krusell-Smith model took 73.90300000000002 seconds.
            - Now solving an economy with 15 Markov states.  This might take a while...
                - Solving a model with 15 states took 7172.353585000001 seconds.
        - Py2:
            - Now solving for the equilibrium of a Cobb-Douglas economy.  This might take a few minutes...
                - Solving the "macroeconomic" aggregate shocks model took 152.691451 seconds.
            - Now solving a two-state Markov economy.  This should take a few minutes...
                - Solving the "macroeconomic" aggregate shocks model took 233.763381 seconds.
            - Now solving a Krusell-Smith-style economy.  This should take about a minute...
                - Solving the Krusell-Smith model took 70.716613 seconds.
            - Now solving an economy with 15 Markov states.  This might take a while...
                - Solving a model with 15 states took 1932.730768 seconds.

- [x] ./ConsumptionSaving/
    - [x] ./ConsIndShockModel-Demos/Try-Alternative-Parameter-Values.py
        - [x] py3
        - [x] py2
    - [x] ./Demos/Fagereng_demo.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 appears to be mildly faster (although some execution, not recorded, wwas clearly faster.)
        - Py3:
            - Time to estimate is 128.98272609710693 seconds.
        - Py2:
            - Time to estimate is 129.340675831 seconds.
    - [x] ./Demos/Chinese_Growth.py
        - [x] py3
        - [x] py2
    - [x] ./Demos/MPC_credit_vs_MPC_income.py
        - [x] py3
        - [x] py2
    - [x] ./Demos/NonDurables_During_Great_Recession.py
        - [x] py3
        - [x] py2

- [x] ./FashionVictim/
    - [x] FashionVictimParams.py
        - [x] py3
        - [x] py2
    - [x] FashionVictimModel.py
        - [x] py3
        - [x] py2
        - NOTE: Py3 error: AttributeError: Can't pickle local object 'FashionVictimType.update.<locals>.<lambda>'
            - Have fixed by addressing issue in HARKparallel.py which explicitly relies on parallelization for Market.solveAgents().
                - Thought this was supposed to be joblib-free?
        - Two things:
            - fixed joblib reliance
            - NOTE: PY3 joblib error where py2 approach worked! Not solved yet; added code to default to serial execution if this doesn't work.
            - NOTE AGAIN: may be able to fix with Numba.prange

- [x] ./SolvingMicroDSOPs/
    - [x] SetupSCFdata.py
        - [x] py3
        - [x] py2
    - [x] EstimationParameters.py
        - [x] py3
        - [x] py2
    - [x] StructEstimation.py
        - [x] py3
        - [x] py2

- [ ] ./Testing/
    - NOTE: this just answers whether these files *run*, not whether the tests all pass. Some fail, but that should be resolved at another time.
    - [x] TractableBufferStockModel_UnitTests.py
        - [x] py3
        - [x] py2
    - [x] MultithreadDemo.py
        - [x] py3
        - [x] py2
        - Note: Py3 again marginally faster:
        -Py3:
            - Solving the basic consumer took 0.6166 seconds.
            - Solving 32 types without multithreading took 30.6242 seconds.
            - Solving 32 types with multithreading took 0.1223 seconds.
        - Py2:
            - Solving the basic consumer took 0.6320 seconds.
            - Solving 32 types without multithreading took 32.3103 seconds.
            - Solving 32 types with multithreading took 0.2214 seconds.
    - [ ] ModelTesting.py
        - Note: because of output message, unclear if code ran correctly. I *think* it did...
        - [ ] py3
        - [ ] py2
    - [x] HARKutilities_UnitTests.py
        - [x] py3
        - [x] py2
    - [ ] Comparison_UnitTests.py
        - Note: because of output message, unclear if code ran correctly. I *think* it did...
        - [ ] py3
        - [ ] py2